### ISSUE TITLE
Bad navigation on edges

### ISSUE THREAD

**Issue by lervag** [sunaku/tmux-navigate#2]
Consider the following setup: A tmux window with two panes split vertically. On the left, Vim is open with two vertical splits. Assume focus is on the left window in the left pane. Moving to the right behaves as expected until we reach the right pane. Now, moving to the right moves us back to the right window in Vim. I would expect that moving right at the right pane would do nothing.

The same behaviour is seen in all directions.

**Comment by sunaku** [comment]
Wrapping focus around on window edges is tmux's native behavior.  Try creating two side-by-side tmux panes and then run `tmux select-pane -R` in the right-hand pane: you'll land on the left-hand pane.

Could you try installing the Vim plugin included in this repo?  I think that may fix this issue and also #1.

**Comment by lervag** [comment]
> Wrapping focus around on window edges is tmux's native behavior. Try creating two side-by-side tmux panes and then run `tmux select-pane -R` in the right-hand pane: you'll land on the left-hand pane.

Yes; but it is not the intuitive behaviour in my opinion. It is not the behaviour in Vim outside tmux and it is not the behaviour with the comparable `vim-tmux-navigator`. Thus, I think this should at least get an option.

> Could you try installing the Vim plugin included in this repo? I think that may fix this issue and also #1.

I did install the Vim plugin already, and it does not affect this issue or #1. The plugin is, as far as I can see, these three lines:

```vim
let progname = substitute($VIM, '.*[/\\]', '', '')
set title titlestring=%{progname}\ %f\ +%l\ #%{tabpagenr()}.%{winnr()}
if &term =~ '^screen' && !has('nvim') | exe "set t_ts=\e]2; t_fs=\7" | endif
```

The second line enables the `title` option with a titlestring that can be used by the tmux plugin to detect Vim's "edges", if I understand correctly.

The third line specifies terminal options. I'm using neovim, so these options are not relevant.

**Comment by sunaku** [comment]
I actually prefer tmux's wrap-around behavior, but feel free to submit a PR for this feature. :tipping_hand_man:  We would need to add more information to Vim's `&titlestring` to enable proper _edge detection_ (not just _change detection_, as currently implemented) and additional logic to consume it and decide whether to navigate.

**Comment by lervag** [comment]
> feel free to submit a PR for this feature

I won't, sorry. I don't have the time.

I think your idea of how to solve the Vim+tmux integration is neat, but the main improvement is that it allows integration through ssh. This is obviously very useful, but at the same time, I mostly work locally, and so the inconvenience in `vim-tmux-navigator` is quite small. I'll therefore revert to it now. I might consider changing to `tmux-navigate` in the future if it is further developed and improved.

Feel free to close the issue if you're not interested in supporting the proposed feature.

**Comment by sunaku** [comment]
I have implemented proper edge detection (no more timeouts!) in the Vim portion of this plugin in commit 8e5823ae5d05bfe1d75b18b88284f42db1093ab4. :tada:  This should make it easier to implement smarter navigation logic, such as the no-wrap feature requested in this issue.

**Comment by lervag** [comment]
>  This should make it easier to implement smarter navigation logic, such as the no-wrap feature requested in this issue.

Nice! But do I understand correctly that it is not currently fully implemented yet?

I'll be glad to test tmux-navigate again if this issue is resolved. :)

**Comment by sunaku** [comment]
Closing as "won't fix" because the requested no-wrap feature is about changing how the `tmux select-pane` command behaves.  Instead, you may submit this feature request [upstream to tmux](https://github.com/tmux/tmux/issues) and ask for a new `select-pane` flag that inhibits focus wrapping.

**Comment by sunaku** [comment]
Closing as "won't fix" because the requested no-wrap feature is about changing how the `tmux select-pane` command behaves.  Instead, you may submit this feature request [upstream to tmux](https://github.com/tmux/tmux/issues) and ask for a new `select-pane` flag that inhibits focus wrapping.
