### ISSUE TITLE
titlestring causes flicking in nvim/tmux on large screens with splits

### ISSUE THREAD

**Issue by HunterWare** [sunaku/tmux-navigate#3]
The current title string causes issues with large screens in tmux/nvim.  The constant updating of the title will cause occasional flickers and since it is changing on cursor movement it causes a lot of cursor flickering.

Changing from:
  set title titlestring=%{progname}\ %f\ +%l\ #%{TmuxNavigateDirections()}
to:
  set title titlestring=%{progname}\ #%{TmuxNavigateDirections()}
will effectively hide the issue.

Admittedly this doesn't happen in vim with Tmux.  But with Neovim in a large (wide screen monitor 500x100) terminal with side by side Tmux splits it gets pretty unusable.  I might suggest that the plugin only set the minimum titlestring it needs, and one could have extra stuff with a tmux-navigate-mid-titlestring that might default to "%f\ +%l\ ".  Then the user could remove the extra stuff by just clearing that variable?

This would allow a non-forking work-around to: https://github.com/neovim/neovim/issues/13095

**Comment by sunaku** [comment]
Thanks for your report. :+1:  Could you please check whether the issue occurs if `%f` is kept and only `%l` is omitted? :thinking:

**Comment by HunterWare** [comment]
I think that the issue is really a neovim problem with the redraw, but when you change the title with every line change that adds up. =)  I didn’t see the issue with %f.

**Comment by sunaku** [comment]
Great! :ok_hand: I have removed `%l` from the titlestring in commit 52da3cdca6e23fda99e05527093d274622b742cd.  Cheers.
